<?php

namespace Teo\Db18nBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends EntityRepository
{
    public function findTranslation($string, $locale, $default)
    {
        $result = $this->findOneBy(array(
            'name' => $string
        ));

        if ($result) {
            $content = $result->getTranslationForLocale($locale, $default);
            if ($content) {
                return $content->getContent();
            }
        }

        return null;
    }
}
