<?php

namespace Teo\Db18nBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LabelTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelTranslationRepository extends EntityRepository
{
}
